# Generated by Django 2.2.2 on 2019-06-24 01:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190616_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=ckeditor.fields.RichTextField(max_length=5120, verbose_name='Descrição da Atividade'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='material',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5120, null=True, verbose_name='Materiais para a Atividade'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='conteudo',
            field=ckeditor.fields.RichTextField(max_length=5120, verbose_name='Conteúdo do Workshop'),
        ),
    ]
