# Generated by Django 2.2.2 on 2019-06-24 01:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190623_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=ckeditor.fields.RichTextField(verbose_name='Descrição da Atividade'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='material',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Materiais para a Atividade'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='conteudo',
            field=ckeditor.fields.RichTextField(verbose_name='Conteúdo do Workshop'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='tempo_necessario',
            field=models.CharField(max_length=255, verbose_name='Tempo previsto para o Workshop'),
        ),
    ]
