# Generated by Django 2.2.2 on 2019-06-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190623_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='nome',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tempo_necessario',
            field=models.CharField(max_length=255, verbose_name='Tempo previsto para a Atividade'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='nome',
            field=models.CharField(max_length=125, verbose_name='Nome do Workshop'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='slug',
            field=models.SlugField(blank=True, max_length=125, unique=True, verbose_name='Apelido do Workshop'),
        ),
    ]
