# Generated by Django 2.2.2 on 2019-06-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190623_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='resumo',
            field=models.CharField(default='resumo', max_length=255, verbose_name='Resumo do Workshop'),
            preserve_default=False,
        ),
    ]
