# Generated by Django 2.2.2 on 2019-06-27 03:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_workshop_resumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=512, verbose_name='Assunto da Mensagem')),
                ('nome', models.CharField(max_length=512, verbose_name='Nome do Autor')),
                ('telefone', models.CharField(max_length=512, verbose_name='Telefone do Autor')),
                ('email', models.CharField(max_length=512, verbose_name='Email do Autor')),
                ('para', models.CharField(max_length=512, verbose_name='Enviado Para')),
                ('ip', models.CharField(max_length=512, verbose_name='IP do autor')),
                ('mensagem', ckeditor.fields.RichTextField(verbose_name='Mensagem')),
            ],
        ),
    ]
